//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dictionary_Blender {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dictionary_Blender.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A dictionary named {0} has already been loaded.
        /// </summary>
        internal static string DictionaryAlreadyLoaded {
            get {
                return ResourceManager.GetString("DictionaryAlreadyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary {0} closed.
        /// </summary>
        internal static string DictionaryClosed {
            get {
                return ResourceManager.GetString("DictionaryClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program currently does not work with dictionaries that contain relations.
        /// </summary>
        internal static string DictionaryHasRelations {
            get {
                return ResourceManager.GetString("DictionaryHasRelations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary {0} loaded.
        /// </summary>
        internal static string DictionaryLoaded {
            get {
                return ResourceManager.GetString("DictionaryLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dictionary could not be loaded because {0} is a name already in use (in {1}) and thus would lead to ambiguity.
        /// </summary>
        internal static string DictionaryNameInUse {
            get {
                return ResourceManager.GetString("DictionaryNameInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No dictionary named {0} has been loaded.
        /// </summary>
        internal static string DictionaryNotFound {
            get {
                return ResourceManager.GetString("DictionaryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program currently only works with one-level dictionaries.
        /// </summary>
        internal static string DictionaryNotOneLevel {
            get {
                return ResourceManager.GetString("DictionaryNotOneLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dictionary could not be loaded due to an error: {0}.
        /// </summary>
        internal static string DictionaryReadError {
            get {
                return ResourceManager.GetString("DictionaryReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary {0} saved to {1}.
        /// </summary>
        internal static string DictionarySaved {
            get {
                return ResourceManager.GetString("DictionarySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} does not exist.
        /// </summary>
        internal static string FileNotExist {
            get {
                return ResourceManager.GetString("FileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item {0} does not have multiple occurrences.
        /// </summary>
        internal static string FlattenMustHaveOccurrences {
            get {
                return ResourceManager.GetString("FlattenMustHaveOccurrences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flattening {0} could not occur because the needed name {1} was not available.
        /// </summary>
        internal static string FlattenNameInvalid {
            get {
                return ResourceManager.GetString("FlattenNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, with {1} occurrences, flattened to {2} items.
        /// </summary>
        internal static string FlattenSuccess {
            get {
                return ResourceManager.GetString("FlattenSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The label for {0} was changed to &quot;{1}&quot;.
        /// </summary>
        internal static string LabelModified {
            get {
                return ResourceManager.GetString("LabelModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is an invalid CSPro object name.
        /// </summary>
        internal static string NameCheckInvalid {
            get {
                return ResourceManager.GetString("NameCheckInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name {0} refers to a currently loaded dictionary and cannot be used.
        /// </summary>
        internal static string NameCheckUsedAsDictionary {
            get {
                return ResourceManager.GetString("NameCheckUsedAsDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name {0} is already used in the dictionary named {1}.
        /// </summary>
        internal static string NameCheckUsedWithinDictionary {
            get {
                return ResourceManager.GetString("NameCheckUsedWithinDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of arguments is not correct. {0} expects {1} arguments.
        /// </summary>
        internal static string ProcessorInvalidNumberArguments {
            get {
                return ResourceManager.GetString("ProcessorInvalidNumberArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of arguments is not correct. {0} expects {1} - {2} arguments.
        /// </summary>
        internal static string ProcessorInvalidNumberArgumentsRange {
            get {
                return ResourceManager.GetString("ProcessorInvalidNumberArgumentsRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No command specified.
        /// </summary>
        internal static string ProcessorNoCommand {
            get {
                return ResourceManager.GetString("ProcessorNoCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized command.
        /// </summary>
        internal static string ProcessorUnrecognizedCommand {
            get {
                return ResourceManager.GetString("ProcessorUnrecognizedCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command {0} is unrecognized.
        /// </summary>
        internal static string ProcessorUnrecognizedCommandSpecify {
            get {
                return ResourceManager.GetString("ProcessorUnrecognizedCommandSpecify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot remove the IDs from your dictionary.
        /// </summary>
        internal static string RemoveIDsDisabled {
            get {
                return ResourceManager.GetString("RemoveIDsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed item {0} located on record {1}.
        /// </summary>
        internal static string RemoveItem {
            get {
                return ResourceManager.GetString("RemoveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed record {0} containing {1} items.
        /// </summary>
        internal static string RemoveRecord {
            get {
                return ResourceManager.GetString("RemoveRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed value set {0} located on item {1}.
        /// </summary>
        internal static string RemoveValueSet {
            get {
                return ResourceManager.GetString("RemoveValueSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} renamed to {1}.
        /// </summary>
        internal static string RenameSuccess {
            get {
                return ResourceManager.GetString("RenameSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} commands successfully run from {1}.
        /// </summary>
        internal static string RunSuccess {
            get {
                return ResourceManager.GetString("RunSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The symbol {0} is contained in more than one dictionary so much be specified with dot notation.
        /// </summary>
        internal static string SymbolAmbiguous {
            get {
                return ResourceManager.GetString("SymbolAmbiguous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dictionary could not be loaded because {0} is the name of a loaded dictionary and thus would lead to ambiguity.
        /// </summary>
        internal static string SymbolNameInUse {
            get {
                return ResourceManager.GetString("SymbolNameInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The symbol {0} is not of the type expected.
        /// </summary>
        internal static string SymbolNotAllowedType {
            get {
                return ResourceManager.GetString("SymbolNotAllowedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No symbol named {0} has been loaded.
        /// </summary>
        internal static string SymbolNotFound {
            get {
                return ResourceManager.GetString("SymbolNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No symbol named {0} is contained in the dictionary {1}.
        /// </summary>
        internal static string SymbolNotFoundInDictionary {
            get {
                return ResourceManager.GetString("SymbolNotFoundInDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item {0} has multiple occurrences so it cannot be unsubitemized.
        /// </summary>
        internal static string UnsubitemizeHasOccurrences {
            get {
                return ResourceManager.GetString("UnsubitemizeHasOccurrences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item {0} has no subitems so it cannot be unsubitemized.
        /// </summary>
        internal static string UnsubitemizeNoSubitems {
            get {
                return ResourceManager.GetString("UnsubitemizeNoSubitems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item {0} has overlapping subitems so it cannot be unsubitemized.
        /// </summary>
        internal static string UnsubitemizeOverlappingSubitems {
            get {
                return ResourceManager.GetString("UnsubitemizeOverlappingSubitems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item {0} has a gap not filled by any subitems so it cannot be unsubitemized as part of a relative positioned dictionary.
        /// </summary>
        internal static string UnsubitemizeSubitemGap {
            get {
                return ResourceManager.GetString("UnsubitemizeSubitemGap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} unsubitemized.
        /// </summary>
        internal static string UnsubitemizeSuccess {
            get {
                return ResourceManager.GetString("UnsubitemizeSuccess", resourceCulture);
            }
        }
    }
}
