//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dictionary_Blender {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dictionary_Blender.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A dictionary named {0} has already been loaded.
        /// </summary>
        internal static string DictionaryAlreadyLoaded {
            get {
                return ResourceManager.GetString("DictionaryAlreadyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary {0} closed.
        /// </summary>
        internal static string DictionaryClosed {
            get {
                return ResourceManager.GetString("DictionaryClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary {0} loaded.
        /// </summary>
        internal static string DictionaryLoaded {
            get {
                return ResourceManager.GetString("DictionaryLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dictionary could not be loaded because {0} is a name already in use (in {1}) and thus would lead to ambiguity.
        /// </summary>
        internal static string DictionaryNameInUse {
            get {
                return ResourceManager.GetString("DictionaryNameInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No dictionary named {0} has been loaded.
        /// </summary>
        internal static string DictionaryNotFound {
            get {
                return ResourceManager.GetString("DictionaryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program can now only work with one-level dictionaries.
        /// </summary>
        internal static string DictionaryNotOneLevel {
            get {
                return ResourceManager.GetString("DictionaryNotOneLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dictionary could not be loaded due to an error: {0}.
        /// </summary>
        internal static string DictionaryReadError {
            get {
                return ResourceManager.GetString("DictionaryReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary {0} saved to {1}.
        /// </summary>
        internal static string DictionarySaved {
            get {
                return ResourceManager.GetString("DictionarySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} does not exist.
        /// </summary>
        internal static string FileNotExist {
            get {
                return ResourceManager.GetString("FileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of arguments is not correct. {0} expects {1} arguments.
        /// </summary>
        internal static string ProcessorInvalidNumberArguments {
            get {
                return ResourceManager.GetString("ProcessorInvalidNumberArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of arguments is not correct. {0} expects {1} - {2} arguments.
        /// </summary>
        internal static string ProcessorInvalidNumberArgumentsRange {
            get {
                return ResourceManager.GetString("ProcessorInvalidNumberArgumentsRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No command specified.
        /// </summary>
        internal static string ProcessorNoCommand {
            get {
                return ResourceManager.GetString("ProcessorNoCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized command.
        /// </summary>
        internal static string ProcessorUnrecognizedCommand {
            get {
                return ResourceManager.GetString("ProcessorUnrecognizedCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dictionary could not be loaded because {0} is the name of a loaded dictionary and thus would lead to ambiguity.
        /// </summary>
        internal static string SymbolNameInUse {
            get {
                return ResourceManager.GetString("SymbolNameInUse", resourceCulture);
            }
        }
    }
}
